POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY2MWIwNGNlYjc5ZDc4ODVlNTJjOTAzYSIsImlhdCI6MTcxMzA4NDUwNywiZXhwIjoxNzEzMDg4MTA3fQ.ecjTIkbY-_t5dfk7w7cuUny-MtcZlwyL4ZgI08dKC8s

{
    "title": "test",
    "author": "test",
    "url": "http://blog.com",
    "likes": 20
}