POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vcnRlbiIsImlkIjoiNjYxYzFlZTI1YThjZjgxYmNkMDFiN2M5IiwiaWF0IjoxNzEzMTE4OTU4LCJleHAiOjE3MTMxMjI1NTh9.DTzsRlx1GERgRMXuHqgNbmDIpTEPHd31-NzUpm3d7wM

{
    "title": "Mortens Blog2",
    "author": "Mortens",
    "url": "http://morten.com",
    "likes": 100
}