name: "healthcheck"

on:
  schedule:
    - cron: "0 10 * * 1"

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@b716ccb6645355dd9fcce8002ce460e5474f7f00
        with:
          url: https://https://patientor-app.onrender.com/api/ping
